name: Qt GUI CI

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.0.0)
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-package:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Build and Package on ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.6.2'
        host: 'linux'
        target: 'desktop'
        modules: 'qtcharts qtmultimedia'

    - name: Patch yunying
      run: |
        sed -i "s/^DEFINES += HAS_CDN/# DEFINES += HAS_CDN/" yunying.pro
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake xvfb
        echo "github.event: toJSON(github.event)"
        
    - name: Configure with qmake
      run: |
        qmake .
        
    - name: Build
      run: |
        make
