name: Qt GUI CI

on:
  [push, pull_request, workflow_dispatch]

jobs:
  build-package:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Build and Package on ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.6.2'
        host: ${{ startsWith(matrix.os, 'macos') && 'mac' || startsWith(matrix.os, 'windows') && 'win' || 'linux' }}
        target: 'desktop'
        modules: 'qtcharts qtmultimedia'

    - name: Patch yunying
      run: |
        sed -i "s/^DEFINES += HAS_CDN/# DEFINES += HAS_CDN/" yunying.pro
    
    - name: Install dependencies
      run: |
        echo "github.event: toJSON(github.event)"
        
    - name: Configure with qmake
      run: |
        qmake .
        
    - name: Build
      run: |
        make
